language: node_js
node_js:
  - 14

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"



# Assuming the .travis.yml file is in the project directory, and there is a separate sub-directory for each service
# Use either `docker-compose` or individual `docker build` commands
# Build
script:
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverseproxy ./udagram-reverseproxy
  - docker build -t udagram-api-user ./udagram-api-user 
  # Tagging
  - docker tag udagram-api-feed h4rryk4y/udagram-api-feed:latest
  - docker tag udagram-api-user h4rryk4y/udagram-api-user:latest
  - docker tag udagram-frontend h4rryk4y/udagram-frontend:latest
  - docker tag reverseproxy h4rryk4y/reverseproxy:latest
# Push
# Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push h4rryk4y/udagram-api-feed:latest
  - docker push h4rryk4y/udagram-api-user:latest
  - docker push h4rryk4y/udagram-frontend:latest
  - docker push h4rryk4y/reverseproxy:latest

  # travis file end