language: node_js
node_js:
  - 13

services:
  - docker

# Installations - Pre-testing
install:
  - echo "nothing needs to be installed"

# Test scripts
before_script:
  - echo "no tests"

# Building and Tagging
script:
  - docker --version # for Logging purposes print docker version
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  - docker tag udagram-reverseproxy h4rryk4y/udagram-reverseproxy:v1

  - docker build -t udagram-frontend ./udagram-frontend
  - docker tag udagram-frontend h4rryk4y/udagram-frontend:v1

  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker tag udagram-api-feed h4rryk4y/udagram-api-feed:v1

  - docker build -t udagram-api-user ./udagram-api-user
  - docker tag udagram-api-user h4rryk4y/udagram-api-user:v1

# DOCKER_PASSWORD and DOCKER_USERNAME set in the Travis repository settings
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push h4rryk4y/udagram-reverseproxy::v1
  - docker push h4rryk4y/udagram-frontend::v1
  - docker push h4rryk4y/udagram-api-user::v1
  - docker push h4rryk4y/udagram-api-feed::v1